name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
      - my-feature-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .

        # Specify path to Dockerfile
        working-directory: ./  # Adjust path if Dockerfile is in a different directory

      - name: Push Docker image to Docker Hub
        run: docker push my-app:${{ github.sha }}

      - name: Deploy Docker container
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: |
          docker run -d --name pr-${{ github.event.number }} my-app:${{ github.sha }}

      - name: Remove Docker container on PR close (not merged)
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.merged
        run: |
          docker rm -f pr-${{ github.event.number }}
