name: PR Deployment

on:
  push:
    branches:
      - main
      - my-feature-branch
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
      - my-feature-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker login and setup
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image
      - name: Build and Push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          context: .  # Adjust context path as needed
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      # Deploy Docker container on PR merge
      - name: Deploy Docker container
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: |
          docker run -d --name pr-${{ github.event.number }} ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      # Remove Docker container on PR close (not merged)
      - name: Remove Docker container
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.merged
        run: |
          docker rm -f pr-${{ github.event.number }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Remove Docker container
        run: |
          docker rm -f pr-${{ github.event.number }}
