name: PR Deployment

on:
  push:
    branches:
      - main
      - my-feature-branch
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
      - my-feature-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          context: .  # Adjust context path as needed
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ GITHUB_SHA::7 }}

      - name: Deploy Docker container
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: |
          docker run -d --name pr-${{ github.event.number }} ${{ secrets.DOCKER_USERNAME }}/my-app:${{ GITHUB_SHA::7 }}

      - name: Remove Docker container on PR close (not merged)
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.merged
        run: |
          CONTAINER_NAME="pr-${{ github.event.number }}"
          if [ "$(docker ps -a -q -f name=${CONTAINER_NAME})" ]; then
            echo "Removing container ${CONTAINER_NAME}"
            docker rm -f ${CONTAINER_NAME}
          else
            echo "No such container: ${CONTAINER_NAME}"
          fi
